### ISSUE TITLE
Add title

### ISSUE THREAD

**Issue by imaichiyyy** [henkaku-center/henkaku-nengajo-frontend#103]
### List
- HENKAKU 年賀状
- HENKAKU Nengajo

...Anything else?

**Comment by maddy020** [comment]
Hey @imaichiyyy 
I would like to work over this issue
Please give me some details and assign it to me

**Comment by imaichiyyy** [comment]
@maddy020 
Thanks for your comment.
Sorry, but as @alecrem commented in #114 , our community is closed so it may be difficult to get your help.
