### ISSUE TITLE
お守りNFTの表示ページを作成

### ISSUE THREAD

**Issue by yawn-c111** [henkaku-center/henkaku-nengajo-frontend#136]
- 管理者がNFTを登録するページ
- ユーザーがNFTを選んでミントするページ

**Comment by imaichiyyy** [comment]
すみません、本issueについて質問と提案をさせてください。

## 質問

以下作業を実施しようとしてますが、認識齟齬あれば教えてください 🙏 
- ヘッダーから「年賀状を作る」メニューを削除し、フッターへ移動
- 「年賀状」という文言まわりを「御守り」へリライト
- 「御守りNFT」について説明文をトップページに追加

## 提案
- 今回デジタル御守りという建付けでNFTを発行しますが、内符という願いが込められた御守りの中身が重要になっています。
- そのため内符をユーザーに意識してもらうため、最初は御守りの画像ではなく内符のイメージを表示し、Mintすることで御守りNFTの画像に切り替わるような仕組みの導入はいかがでしょうか？
- 以下がそのイメージです。

### Mint前

https://github.com/henkaku-center/henkaku-nengajo-frontend/assets/18373906/126230da-b6ac-402b-b29c-8b15c4eaff6e

### Mint後

![minted](https://github.com/henkaku-center/henkaku-nengajo-frontend/assets/18373906/02e0591b-cd24-4cba-8c35-b7ba9c619b1a)

**Comment by geeknees** [comment]
Discordで回答済みなのですが、こちら確認させていただいたので、一応記録としてコメントを残します。

> ヘッダーから「年賀状を作る」メニューを削除し、フッターへ移動

ここらへんは削除はせず、年賀状NFTとお守りNFTは両方共存する形になります。

> そのため内符をユーザーに意識してもらうため、最初は御守りの画像ではなく内符のイメージを表示し、Mintすることで御守りNFTの画像に切り替わるような仕組みの導入はいかがでしょうか？

これはいい感じだと思います。yawnさん、A.J.さんも賛同されているので、導入でよいかと思います。

**Comment by imaichiyyy** [comment]
@geeknees 
コメントありがとうございます。

> ここらへんは削除はせず、年賀状NFTとお守りNFTは両方共存する形になります。

ありがとうございます！
Discordでyawnさんにもお伝えしましたが、僕が勘違いをしていたことがわかりましたので共存する形で対応します。

**Comment by imaichiyyy** [comment]
リリースしたのでこちらクローズしたいと思います 🙏
