### ISSUE TITLE
Add header and footer

### ISSUE THREAD

**Issue by alecrem** [henkaku-center/henkaku-nengajo-frontend#23]
Some reference:

- [omise layout code](https://github.com/henkaku-center/omise-interface/blob/main/components/layouts/layout.tsx)
- [Chakra UI's Flex](https://chakra-ui.com/docs/components/flex/usage)

**Comment by imaichiyyy** [comment]
## Menu items displayed in the header
Is there anything else you would like to set for the menu besides the following that you have in mind?
(or if there is any functionality that we may not need 🙏 )
### Home
### Register
- Go to the image registration page.
### Nengajo
- Go to the list of registered New Year's cards (you can mint them on this screen).
### Light / DarkMode
- Switch between Light and Dark Mode function.
### i18n
- Support for locales (en, ja).

## About footer items
In the footer of omise, there are links to Twitter and GitHub repositories, do you want to display these as well?

**Comment by alecrem** [comment]
Thank you! This is very detailed and helpful.

> Register

SGTM 🙆

> Nengajo

I think it makes sense for the home page to be the list of registered nengajos. What does everyone think?

> Light / DarkMode and i18n

These are not implemented and I think it would make sense to leave them for a future PR. But please keep them in mind when thinking about the layout. It's also okay if you would like to include dummy buttons for these in the first PR, if it is not going to take much longer.

> In the footer of omise, there are links to Twitter and GitHub repositories, do you want to display these as well?

I think that's a good idea. What does everyone think?

**Comment by yu23ki14** [comment]
> Nengajo

It would be nice to display 15~20 new registered Nengajo in home page and also create Nengajo Page for display all Nengajo.

We need to create my page for display holding Nengajo, so adding something like a "Mypage" is nice

**Comment by alecrem** [comment]
> It would be nice to display 15~20 new registered Nengajo in home page and also create Nengajo Page for display all Nengajo.

@yu23ki14 What else do we display on the home page? It could be confusing to show almost the same content on two different pages. We probably want paging when there are enough nengajos, anyway, so the first page shouldn't be too much anyway.

> We need to create my page for display holding Nengajo, so adding something like a "Mypage" is nice

Sounds great! Thank you, we forgot about this page... How do we call it? Collection?

**Comment by imaichiyyy** [comment]
@alecrem 
Thank you for your comment.
I will take "omise" as a reference.

The "i18n" function is not so difficult to develop, so we will it.
However, "Light / Dark mode" seems to be a low-priority feature, so I'll just display the button for now.

**Comment by imaichiyyy** [comment]
@alecrem @yu23ki14 

Thank you for your comment.
In summary, the menu items are as follows?

### Home
- Display 15~20 new registered "Nengajo".
- Opening and closing hours are shown.

### Nengajo
- Search registered all "Nengajo"

### Collection
(Which of the following?)
- Does it show "Nengajo" that user have minted.
- Or do you want to see the "Nengajo" user have registered.
- Or both

### Register
- User can register your own images as "Nengajo".
