### ISSUE TITLE
Move "disconnect button" to Header component.

### ISSUE THREAD

**Issue by imaichiyyy** [henkaku-center/henkaku-nengajo-frontend#52]
I think the "disconnect button" should be moved to the header. (but only the disconnect button)
The reason is that although it is a required feature for users, it is not a high priority.

**Comment by alecrem** [comment]
I agree!

I guess this means making a new Disconnect component, which only returns (shows) something if the user is connected. And changing the Connect component so that it only returns something if the iser is disconnected.

**Comment by imaichiyyy** [comment]
Yes, exactly!
