### ISSUE TITLE
Detail page for a particular registered token

### ISSUE THREAD

**Issue by alecrem** [henkaku-center/henkaku-nengajo-frontend#9]
Users should be able to view details about the token or mint.

(This issue is just the layout/design.)

**Comment by dueyama** [comment]
こちらは、omise だと、

pages/badges/[id].tsx

に対応するものでしょうか？

pages/badges/index.tsx

に対応するものは futa さんが作成しているという認識です。

**Comment by alecrem** [comment]
@dueyama さん、同じように理解しています。

**Comment by imaichiyyy** [comment]
@alecrem さん  
こちら対応してもいいでしょうか？🙋🏻

**Comment by alecrem** [comment]
@imaichiyyy さんもちろんいいと思いますが、 @dueyama さんは先程確認していたのですね。

@dueyama さんは、このissueに対応するつもりだったのでしょうか？

**Comment by dueyama** [comment]
これ見てて、一覧だけで良いんじゃ無いかと思って discord に書いたのですが。ただ、一つの detail かけたら、それを一覧に使えますよね。component みたいになれば。私には多分難しいので、 @imaichiyyy さんにお願いしたいです。

**Comment by alecrem** [comment]
誰がやってもみんな勉強になりますね！

それでは @imaichiyyy さん、assignしました。よかったらDeWorkでも申し込んでください。

**Comment by imaichiyyy** [comment]
@dueyama さん
なるほど、こちらの話題がこのissueに紐づいていたのですね。
https://discord.com/channels/913694033031864350/1027861277814571038/1048227982659035166
まず、理解が足りなかった事失礼いたしました。。🙇🏻

>これ見てて、一覧だけで良いんじゃ無いかと思って discord に書いたのですが。ただ、一つの detail かけたら、それを一覧に使えますよね。component みたいになれば。私には多分難しいので、 @imaichiyyy さんにお願いしたいです。

またこちらの点承知しました。対応します🙏
（一応考えたのですが、ユーザーはすでに投稿された年賀状をmintする訳ですから、大きい画像で確認したい欲求はあるのかなと。ですので、detailページを作るかまたは一覧ページのであればモーダルウィンドウで大きい画像が表示されたほうが良いかなと思ってました。）

**Comment by dueyama** [comment]
すみません、分かりにくくて😅確かに大きくしてみたいですね！

**Comment by alecrem** [comment]
大きい画像、いいと思います！

自分の作った年賀状の告知するとき、URLがあると便利ですね。

Modalよりページがいいでしょうか？

**Comment by imaichiyyy** [comment]
@dueyama さん
ありがとうございます！

@alecrem さん
そうですね、おっしゃるとおりURLを簡単にシェアできるdetailの方が良いのかなと思います🙆🏻

**Comment by imaichiyyy** [comment]
あーでも一覧で複数選択してmintするということは、一覧でもModalで大きい画像が見れたほうがいいですね。。

**Comment by alecrem** [comment]
ショッピングカートは、もしかして別issueでしょうか？

List->detail->cart(mint)
List(複数選択)->cart(mint)

一覧のものも大きくなってもいいと思います！それも別issueでしょうか？

**Comment by imaichiyyy** [comment]
>List->detail->cart(mint)
List(複数選択)->cart(mint)

ここの仕様はよくわかっていません。。

>ショッピングカートは、もしかして別issueでしょうか？
一覧のものも大きくなってもいいと思います！それも別issueでしょうか？

とりあえずこのissueはlayoutを作るのみにさせていただき、  
その他のものは別issueが良いかなと思っていますがいかがでしょうか？

**Comment by alecrem** [comment]
> List->detail->cart(mint)
> List(複数選択)->cart(mint)

確かに分かりにくいですね！すみませんでした。
1つミントする（もらう）人とまとめてミントする人の流れがこれかな、と思っていましたけど、detailページはやっぱり告知のリンク先にするほうがいいでしょうか？

- 告知を見てきて、1つミント: detail->cart(mint)
- 告知を見てきて、複数つミント: detail->index->cart(mint)
- 一覧から1つ選んでミント: List->cart(mint)
- 一覧から複数つ選んでミント: List->cart(mint)

**Comment by imaichiyyy** [comment]
@alecrem 
ありがとうございます！

> 1つミントする（もらう）人とまとめてミントする人の流れがこれかな、と思っていましたけど、detailページはやっぱり告知のリンク先にするほうがいいでしょうか？

この議論は別issueで判断するとして、いったん一覧でもdeitalでも使えるようにコンポーネントとして制作します！

**Comment by alecrem** [comment]
@imaichiyyy さん、いいですね、それ！🥺
楽しみです🙇勉強になりそう。
